### ISSUE TITLE
Shall we use 'int' in split ?

### ISSUE THREAD

**Issue by PhompAng** [PhompAng/Cost-Spliter#2]
![capture](https://cloud.githubusercontent.com/assets/2058809/7064290/c258bfce-ded7-11e4-9f86-92b22b5c024a.JPG)

**Comment by ton212** [comment]
อันนี้น่าจะโอเคแล้วนะ ปล่อยผ่านไปเลย
ตอนสุดท้ายเดี๋ยวคนจ่ายก็จ่ายกันเองตามยอดที่มันจ่ายได้จริงๆ อยู่แล้วมั้ง

On Thursday, April 9, 2015, PhompAng notifications@github.com wrote:

> Assigned #2 https://github.com/PhompAng/Cost-Spliter/issues/2 to @ton212
> https://github.com/ton212.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PhompAng/Cost-Spliter/issues/2#event-277025334.

## 

Tonsai Singhkangwan (Film)
Tel : 081-804-8870 (AIS)
