### ISSUE TITLE
Auto or manual fill 'datetime' ?

### ISSUE THREAD

**Issue by PhompAng** [PhompAng/Cost-Spliter#4]

**Comment by ton212** [comment]
อันนี้คือตอนเพิ่มค่าใช้จ่ายหรอ

On Thursday, April 9, 2015, PhompAng notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/PhompAng/Cost-Spliter/issues/4.

## 

Tonsai Singhkangwan (Film)
Tel : 081-804-8870 (AIS)

**Comment by PhompAng** [comment]
yes
